
sudo: false

language: 'php'

php:
  - '7.1'

cache:
  directories:
    - '$HOME/.composer/cache'

before_install:
    - 'export COMPOSER_NO_INTERACTION=1'
    - 'export COMPOSER_DISABLE_XDEBUG_WARN=1'

install:
  - 'composer install --no-progress'

script:
  - 'composer run lint'
  - 'composer run test'

after_success:
  - 'bash <(curl -s https://codecov.io/bash)'

notifications:
  email: false
