version: 2.1

orbs:
    codecov: 'codecov/codecov@3.0.0'

.env_common: &env_common
    SHELL: '/bin/bash'

.env_xdebug: &env_xdebug
    XDEBUG_MODE: 'coverage'

.env_composer: &env_composer
    COMPOSER_NO_INTERACTION: '1'
    COMPOSER_MEMORY_LIMIT: '-1'
    COMPOSER_DISABLE_XDEBUG_WARN: '1'

executors:
    php800:
        environment:
            <<: *env_common
            <<: *env_xdebug
            <<: *env_composer

        docker:
            -
                name: 'main'
                image: 'circleci/php:8.0'

    php704:
        environment:
            <<: *env_common
            <<: *env_xdebug
            <<: *env_composer

        docker:
            -
                name: 'main'
                image: 'circleci/php:7.4'

commands:
    composer_install:
        description: 'Install Composer dependencies with cache restore and save'
        steps:
            -
                restore_cache:
                    name: 'Composer - cache restore'
                    keys:
                        - 'composer-{{ checksum "./composer.lock" }}-2'

            -
                run:
                    name: 'Composer - install'
                    command: >
                        composer install --no-progress

            -
                save_cache:
                    name: 'Composer - cache save'
                    key: 'composer-{{ checksum "./composer.lock" }}-2'
                    paths:
                        - '~/.composer/cache/'
                        - '~/.cache/composer/'

    lint:
        description: 'Run lint'
        steps:
            -
                run:
                    name: 'Run PHPCS'
                    command: 'composer run lint'

    test_unit:
        description: 'Run unit tests'
        steps:
            -
                run:
                    name: 'Run unit tests'
                    command: 'composer run test'
            -
                store_test_results:
                    name: 'Store unit test results'
                    path: './tests/_output/machine/junit'
            -
                codecov/upload:
                    flags: 'unit'
                    file: './tests/_output/machine/coverage/coverage.xml'

jobs:
    build:
        executor: 'php704'
        working_directory: '~/repo'
        steps:
            - 'checkout'
            - 'composer_install'
    lint:
        executor: 'php704'
        working_directory: '~/repo'
        steps:
            - 'checkout'
            - 'composer_install'
            - 'lint'
    test_php800:
        executor: 'php800'
        working_directory: '~/repo'
        steps:
            - 'checkout'
            - 'composer_install'
            - 'test_unit'
    test_php704:
        executor: 'php704'
        working_directory: '~/repo'
        steps:
            - 'checkout'
            - 'composer_install'
            - 'test_unit'

workflows:
    lint_and_test:
        jobs:
            -
                build: {}
            -
                lint:
                    requires:
                        - 'build'
            -
                test_php800:
                    requires:
                        - 'build'
            -
                test_php704:
                    requires:
                        - 'build'
